// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Runtime queries use the pooled connection (port 6543 via Supavisor)
    url: process.env["DATABASE_URL"],
    // Migrations use the direct connection (port 5432, required by Prisma migrate)
    directUrl: process.env["DIRECT_URL"],
  },
});
